version: '3.8'

services:
  postgres:
    image: postgres:16 # Use the appropriate PostgreSQL version (16 in this case)
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ezrantn
      POSTGRES_DB: hyfit-db
    ports:
      - '5432:5432' # Exposes PostgreSQL on port 5432 to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
